# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82621d1bc4e179bdbe86b4efd41a9a96198e2103530c111ef80986b9765b5ca2d28a2f83049902de46c482cc324175daf2904ac767e91ab42d324e1f6b6097b3

test:
  secret_key_base: 7bb589d645dceb59e84758157cfea05e3113de830c6a37d36af4561e24384ee5dc85d8544c09e0b2398d33070ca5a0a4c6278839ff67440e9423aebf833c3def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
